import sys
import os
import subprocess
from time import sleep
import socket

###################################
# ELASTICSEARCH
###################################
from elasticsearch import Elasticsearch
from elasticsearch.exceptions import AuthenticationException
from elasticsearch.helpers import bulk
import logging
from elasticsearch.exceptions import NotFoundError


# Enabling logging so that we can see it in K8S Logs
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(), logging.FileHandler("app.log", mode="a")],
)
logger = logging.getLogger()


def get_elastic_client(password):
    """
    connect using the http authentification and the password generated by ELASTIC
    when creating the pod, changes everytime it is launched in a new pod, so loaded as a paremeter

    return : elastic client
    """
    client = Elasticsearch(
        "https://quickstart-es-http.default.svc:9200",
        http_auth=("elastic", password),
        verify_certs=False,
    )

    try:
        response = client.info()
    except AuthenticationException:
        print("Authentication failed. Please check your credentials.")
    except Exception as e:
        print(f"Error connecting to Elasticsearch: {e}")

    return client
